version: "3"

services:
  vote:
    image: rwlaub/voting-vote
    command: python app.py
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"

  redis:
    image: redis:alpine
    ports: ["6379"]

  worker:
      image: rwlaub/voting-worker

  db:
    image: postgres:9.4

  result:
    image: rwlaub/voting-result
    command: nodemon --debug server.js
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
